from manim import *

class Eq(Scene):
    def construct(self):
        line1 = MathTex("r(x,y,z) = r(a \cos t \cos s, a \cos t \sin s, a \sin t)")
        self.play(Write(line1))
        self.play(line1.animate.shift(UP*2))
        line2 = MathTex("\\frac{\partial r}{\partial s} = (-a \cos t \sin s, a \cos t \cos s, 0)").next_to(line1, DOWN).align_to(line1, LEFT)
        line3 = MathTex("\\frac{\partial r}{\partial t} = (-a \sin t \cos s, -a \sin t \sin s, a \cos t)").next_to(line2, DOWN).align_to(line1, LEFT)
        self.wait(1)
        self.play(Write(line2))
        self.wait(1)
        self.play(Write(line3))
        self.wait(1)
        self.play(FadeOut(line1, line2, line3))
        line4 = MathTex("\\frac{\partial r}{\partial s}\\times\\frac{\partial r}{\partial t}")
        self.play(Write(line4))
        self.play(line4.animate.shift(UP*2))
        self.wait(1)
        line5 = MathTex("\\begin{vmatrix} -a \cos t \sin s & a \cos t \cos s & 0 \\\ - a \sin t \cos s & -a \sin t \sin s & a \cos t \end{vmatrix}")
        self.play(Write(line5))
        line6 = MathTex("(a^2\cos(s)\cos^2(t), a^2\sin(s)\cos^2(t), 0.5a^2\sin(2t))").next_to(line5, DOWN, buff=1)
        self.wait(1)
        self.play(Write(line6))
        self.wait(1)
        self.play(FadeOut(line4, line5, line6))
        line7 = MathTex("||\\frac{\partial r}{\partial s}\\times\\frac{\partial r}{\partial t}||")
        self.play(Write(line7))
        self.wait(1)
        line8 = MathTex("||(a^2\cos(s)\cos^2(t), a^2\sin(s)\cos^2(t), 0.5a^2\sin(2t)||")
        self.play(Transform(line7, line8))
        self.wait(1)
        line9 = MathTex("= a^2 \cos t").next_to(line7, DOWN)
        newl = MathTex("a^2 \cos t").next_to(line7, DOWN)
        self.play(Write(line9))
        self.wait(1)
        self.play(FadeOut(line7, line8))
        self.play(Transform(line9,newl))
        self.play(line9.animate.shift(UP*3))
        line10 = MathTex("a^2\int_{0}^{2\pi}\int_{-\\frac{\pi}{2}}^{\\frac{\pi}{2}}\cos t \, dt \, ds").next_to(line9, DOWN)
        self.wait(1)
        self.play(Write(line10))
        line11 = MathTex("= a^2\int_{0}^{2\pi}2ds").next_to(line10, DOWN)
        self.wait(1)
        self.play(Write(line11))
        self.wait(1)
        line12 = MathTex("= \\boxed{4\pi a^2}", font_size=100).next_to(line11, DOWN)
        self.play(Write(line12))
        self.wait(1)

      

        
